name: Go

on:
  push:
    branches: []
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: actions/checkout@v2

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o licensing_service cmd/licensing_service/main.go

    - run: mkdir -p acme-demo
    - run: mv licensing_service acme-demo/

    - uses: actions/upload-artifact@v2
      with:
        name: licensing_service
        path: acme-demo/

  build_docker:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: licensing_service
        path: acme-demo

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: dcleric/acme-demo
        tag_with_ref: true
