name: Go

on:
  push:
    branches: []
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o licensing_service cmd/main.go

    - run: mkdir -p acme-demo

    - uses: actions/upload-artifact@v2
      with:
        name: licensing_service
        path: acme-demo
